# Generated by Django 3.0.8 on 2020-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('call', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('price', models.CharField(default=1, max_length=25, verbose_name='가격')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='수량')),
            ],
        ),
    ]
